---
- name: Start Apache
  service: name=apache2 state=started enabled=yes

- name: Start MySQL
  service: name=mysql state=started enabled=yes

- name: Reload Apache
  service: name=apache2 state=reloaded
